services:
  django:
    environment:
      BASE_DOMAIN: "q.lewandowicz.it"
    build: .
    network_mode: "host"
    restart: unless-stopped
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:33003"
    volumes:
      - .:/backend_app
      - /var/run/dbus:/var/run/dbus
    ports:
      - "33003:33003"
