services:
  django:
    environment:
      BASE_DOMAIN: "supplies.wikamaciek.pl"
    build: .
    network_mode: "host"
    restart: always
    command: bash -c "python manage.py migrate && python manage.py runserver_plus 0.0.0.0:33003 --cert-file ssl-certs/cert.pem"
    volumes:
      - .:/backend_app
      - /var/run/dbus:/var/run/dbus
    ports:
      - "33003:33003"
