# Generated by Django 5.0 on 2024-05-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0004_supply_created_at_supply_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="bar_code",
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
