# Generated by Django 5.0 on 2024-06-06 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0006_alter_supply_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supply",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplies",
                to="supplies.product",
            ),
        ),
    ]
