# Generated by Django 5.0 on 2024-06-27 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0007_alter_supply_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=1, max_digits=5)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demand_tag",
                        to="supplies.product",
                    ),
                ),
            ],
        ),
    ]
