# Generated by Django 5.0 on 2025-04-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0009_supply_printed_once_supply_scheduled_print"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supply",
            name="expiration_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
