# Generated by Django 5.0 on 2025-04-13 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0010_alter_supply_expiration_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="demandtag",
            old_name="amount",
            new_name="min_amount",
        ),
        migrations.RemoveField(
            model_name="demandtag",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="demand_tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="supplies.demandtag",
            ),
        ),
    ]
