# Generated by Django 5.0 on 2025-04-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0011_rename_amount_demandtag_min_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandtag",
            name="name",
            field=models.CharField(default="", max_length=63),
            preserve_default=False,
        ),
    ]
