# Generated by Django 5.0 on 2025-04-13 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0012_demandtag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="demand_tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="supplies.demandtag",
            ),
        ),
    ]
