# Generated by Django 5.0 on 2025-04-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0013_alter_product_demand_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="demand_tag",
        ),
        migrations.AddField(
            model_name="product",
            name="demand_tag",
            field=models.ManyToManyField(
                related_name="products", to="supplies.demandtag"
            ),
        ),
    ]
