# Generated by Django 5.0 on 2025-04-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0014_remove_product_demand_tag_product_demand_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(blank=True, to="supplies.category"),
        ),
        migrations.AlterField(
            model_name="product",
            name="demand_tag",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="supplies.demandtag"
            ),
        ),
    ]
