# Generated by Django 5.0 on 2025-04-13 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0015_alter_product_categories_alter_product_demand_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="demand_tag",
        ),
    ]
