# Generated by Django 5.0 on 2025-04-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0016_remove_product_demand_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandtag",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="demand_tags", to="supplies.product"
            ),
        ),
    ]
