name: Python ci

on: [ push ]

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/local.txt
      - name: black
        run: |
          black --check --diff --exclude migrations --line-length 88 ware_home config
      - name: isort
        run: |
          isort --profile black --check-only ware_home config

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/local.txt
      - name: Test with pytest
        env:
          SECRET_KEY: 'dummy_tests_sec_key'
          STATIC_DIR: 'not_relevant_for_tests'
        run: |
          python -m pytest ware_home/tests
